# Generated by Django 4.2.6 on 2023-11-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveymodel',
            name='for_everyone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='votemodel',
            name='for_everyone',
            field=models.BooleanField(default=True),
        ),
    ]
