# Generated by Django 4.2.6 on 2023-11-10 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0002_surveymodel_for_everyone_votemodel_for_everyone'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='VoteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=255)),
                ('vote_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vote.votemodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='surveymodel',
            name='who_create',
        ),
        migrations.RemoveField(
            model_name='surveyquestionmodel',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='surveyuser',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='surveyuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='voteansweroption',
            name='vote_model',
        ),
        migrations.DeleteModel(
            name='SurveyAnswerOption',
        ),
        migrations.DeleteModel(
            name='SurveyModel',
        ),
        migrations.DeleteModel(
            name='SurveyQuestionModel',
        ),
        migrations.DeleteModel(
            name='SurveyUser',
        ),
        migrations.DeleteModel(
            name='VoteAnswerOption',
        ),
        migrations.AddField(
            model_name='voteanswer',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.voteoption'),
        ),
        migrations.AddField(
            model_name='voteanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
