# Generated by Django 4.2.6 on 2023-11-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_voteanswer_voteoption_remove_surveymodel_who_create_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voteoption',
            unique_together={('choice', 'vote_model')},
        ),
    ]
