# Generated by Django 4.2.6 on 2023-11-17 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_alter_voteoption_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voteanswer',
            name='answer',
        ),
    ]
