# Generated by Django 4.2.6 on 2023-11-20 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0006_votemodel_rerunable'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('published', models.BooleanField(default=False)),
                ('for_everyone', models.BooleanField(default=True)),
                ('rerunable', models.BooleanField(default=False)),
                ('who_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.surveymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('free_answer', models.CharField(max_length=255, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vote.surveymodel')),
            ],
            options={
                'unique_together': {('question', 'survey')},
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=255)),
                ('answer', models.BooleanField(null=True)),
                ('question_survey_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vote.surveyquestionmodel')),
            ],
        ),
    ]
